---
# tasks file for server

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required software
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - apache2
    - mysql-server
    - php-mysql
    - php
    - libapache2-mod-php
    - python3-mysqldb
